/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bcms;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainAppTest {
    @Test void appCanBeInstantiated() {
        // Basic test to ensure MainApp can be instantiated
        // For JavaFX applications, testing the UI often requires more setup (e.g., TestFX)
        // This is a very basic placeholder test.
        MainApp classUnderTest = new MainApp(); 
        assertNotNull(classUnderTest, "app should be able to be instantiated");
    }
}
